server:
  port: 8080

spring:
  application:
    name: movie_app

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/movie_app}
    username: ${DB_USERNAME:movie_app}
    password: ${DB_PASSWORD:movie_app}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
